In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('russia_losses_equipment.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(x)

[['2022-02-26' 3 27 26 146 706 49 1 4 30 60 2 2 0]
 ['2022-02-28' 5 29 29 150 816 74 1 21 291 60 3 2 5]
 ['2022-03-01' 6 29 29 198 846 77 1 24 305 60 3 2 7]
 ['2022-03-02' 7 30 31 211 862 85 1 40 355 60 3 2 9]
 ['2022-03-03' 8 30 31 217 900 90 1 42 374 60 3 2 11]
 ['2022-03-04' 9 33 37 251 939 105 1 50 404 60 3 2 18]
 ['2022-03-05' 10 39 40 269 945 105 1 50 409 60 3 2 19]
 ['2022-03-06' 11 44 48 285 985 109 1 50 447 60 4 2 21]
 ['2022-03-07' 12 46 68 290 999 117 1 50 454 60 7 3 23]
 ['2022-03-08' 13 48 80 303 1036 120 1 56 474 60 7 3 27]
 ['2022-03-09' 14 49 81 317 1070 120 1 56 482 60 7 3 28]
 ['2022-03-10' 15 49 81 335 1105 123 1 56 526 60 7 3 29]
 ['2022-03-11' 16 57 83 353 1165 125 1 58 558 60 7 3 31]
 ['2022-03-12' 17 58 83 362 1205 135 1 62 585 60 7 3 33]
 ['2022-03-13' 18 74 86 374 1226 140 1 62 600 60 7 3 34]
 ['2022-03-14' 19 77 90 389 1249 150 1 64 617 60 8 3 34]
 ['2022-03-15' 20 81 95 404 1279 150 1 64 640 60 9 3 36]
 ['2022-03-16' 21 84 108 430 1375 190 1 70 819 60 11 3 43

In [7]:
print(y)

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan 10.
 10.]


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [10]:
print(x)

[['2022-02-26' 3.0 27.0 26 146 706 49 1 4 30 60 2 2 0]
 ['2022-02-28' 5.0 29.0 29 150 816 74 1 21 291 60 3 2 5]
 ['2022-03-01' 6.0 29.0 29 198 846 77 1 24 305 60 3 2 7]
 ['2022-03-02' 7.0 30.0 31 211 862 85 1 40 355 60 3 2 9]
 ['2022-03-03' 8.0 30.0 31 217 900 90 1 42 374 60 3 2 11]
 ['2022-03-04' 9.0 33.0 37 251 939 105 1 50 404 60 3 2 18]
 ['2022-03-05' 10.0 39.0 40 269 945 105 1 50 409 60 3 2 19]
 ['2022-03-06' 11.0 44.0 48 285 985 109 1 50 447 60 4 2 21]
 ['2022-03-07' 12.0 46.0 68 290 999 117 1 50 454 60 7 3 23]
 ['2022-03-08' 13.0 48.0 80 303 1036 120 1 56 474 60 7 3 27]
 ['2022-03-09' 14.0 49.0 81 317 1070 120 1 56 482 60 7 3 28]
 ['2022-03-10' 15.0 49.0 81 335 1105 123 1 56 526 60 7 3 29]
 ['2022-03-11' 16.0 57.0 83 353 1165 125 1 58 558 60 7 3 31]
 ['2022-03-12' 17.0 58.0 83 362 1205 135 1 62 585 60 7 3 33]
 ['2022-03-13' 18.0 74.0 86 374 1226 140 1 62 600 60 7 3 34]
 ['2022-03-14' 19.0 77.0 90 389 1249 150 1 64 617 60 8 3 34]
 ['2022-03-15' 20.0 81.0 95 404 1279 150 1 64 640 

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [12]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 3.0 27.0 26 146 706 49 1 4 30 60 2 2 0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 5.0 29.0 29 150 816 74 1 21 291 60 3 2 5]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 6.0 29.0 29 198 846 77 1 24 305 60 3 2 7]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 7.0 30.0 31 211 862 85 1 40 355 60 3 2 9]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 8.0 30.0 31 217 900 90 1 42 374 60 3 2 11]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 9.0 33.0 37 251 939 105 1 50 404 60 3 2 18]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 10.0 39.0 40 269 945 105 1 50 409 60 3 2 19]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 11.0 44.0 48 285 985 109 1 50 447 60 4 2 21]
 [0.0 0.0 0.0 0.0

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [14]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]


In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [16]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 6.0 29.0 29 198 846 77 1 24 305 60 3 2 7]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 18.0 74.0 86 374 1226 140 1 62 600 60 7 3 34]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 8.0 30.0 31 217 900 90 1 42 374 60 3 2 11]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 20.0 81.0 95 404 1279 150 1 64 640 60 9 3 36]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 11.0 44.0 48 285 985 109 1 50 447 60 4 2 21]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 5.0 29.0 29 150 816 74 1 21 291 60 3 2 5]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 17.0 58.0 83 362 1205 135 1 62 585 60 7 3 33]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 3.0 27.0 26 146 706 49 1 4 30 60 2 2 0]
 [0.0 0.0 

In [17]:
print(x_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 7.0 30.0 31 211 862 85 1 40 355 60 3 2 9]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 19.0 77.0 90 389 1249 150 1 64 617 60 8 3 34]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 10.0 39.0 40 269 945 105 1 50 409 60 3 2 19]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 14.0 49.0 81 317 1070 120 1 56 482 60 7 3 28]]


In [18]:
print(y_train)

[1 1 1 1 1 1 1 1 0 0 1 1 1 1 1]


In [19]:
print(y_test)

[1 1 1 1]


In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:,3:])

In [21]:
print(x_train)

[[0.0 0.0 1.0 0.0 -0.2672612419124243 -0.2672612419124244 0.0
  -0.2672612419124243 -0.2672612419124244 -0.2672612419124244 0.0
  -0.2672612419124244 -0.2672612419124244 -0.26726124191242434
  -0.2672612419124243 0.0 -0.2672612419124243 -0.26726124191242434
  -0.26726124191242434 -1.2155835411881712 -1.113348713147083
  -1.2863501208956227 -1.134792974801966 -1.0828401875947782
  -1.0999740955896375 0.0 -1.364776362624457 -0.9263727027709868 0.0
  -1.0800383838987377 -1.224744871391589 -1.3036137368957639]
 [0.0 0.0 0.0 0.0 -0.2672612419124243 -0.2672612419124244 0.0
  -0.2672612419124243 -0.2672612419124244 -0.2672612419124244 0.0
  -0.2672612419124244 -0.2672612419124244 -0.26726124191242434
  3.7416573867739404 0.0 -0.2672612419124243 -0.26726124191242434
  -0.26726124191242434 0.8486149249804216 1.0969759379537438
  0.6882088618077116 0.7709662195219462 0.7723413781672408
  0.49921901261375873 0.0 0.6770150460263055 0.539721435198118 0.0
  0.3287073342300508 0.8164965809277257 0.75